-- 19, 20, 26, 27: COUNT, LEFT JOIN, GROUP BY and HAVING
-- Quantidade de estudante por curso de exatas

SELECT C.NOME, COUNT(A.CPF_ESTUDANTE)
FROM ACESSA A
LEFT JOIN CURSO C
ON A.COD_CURSO = C.CURSO_ID
GROUP BY A.COD_CURSO, C.NOME
HAVING C.NOME LIKE '%Exatas%'